kind: Pod
apiVersion: v1
metadata:
  name: myaks_pod
spec:
  containers:
  - name: myaks_container
    image: mbrahim86/lamp-app-product
    volumeMounts:
    - mountPath: "/mnt/azure/"
      name: volume
  volumes:
    - name: volume
      azureDisk:
        kind: Managed
        diskName: myaks-pv 
        diskURI: /subscriptions/<subscriptions>/resourceGroups/myaksGroup/providers/Microsoft.Compute/disks/myaks-pv   
